Add support for providing sentinel username.
spring-projects/spring-data-redis pull request #2224
Opened 2022-01-04 21:26 UTC by vikasgarghb

- [ X ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ X ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ X ] You submit test cases (unit or integration tests) that back your changes.
- [ X ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

This pull request allows you to provide username for sentinel which in turn allows support for ACL based authentication provided with redis 6.

This covers the issue mentioned here: https://github.com/spring-projects/spring-data-redis/issues/2218

2022-01-04 21:26 UTC, pivotal-cla commented
@vikasgarghb Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2224)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2224) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-01-04 21:28 UTC, pivotal-cla commented
@vikasgarghb Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2224)!

2022-01-05 14:47 UTC, mp911de requested changes
Thanks for your pull request. I added comments regarding minor issues. Also, the formatting seems odd, care to have a look? You can find the formatter settings at https://github.com/spring-projects/spring-data-build/tree/main/etc/ide

2022-01-05 14:47 UTC, mp911de commented on src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConverters.java
> +			if (StringUtils.hasText(sentinelUsername)) {
We should set the authentication with username only if a password is present in addition to the username check. Having a username without a password isn't supported in the authentication scheme.

2022-01-05 14:47 UTC, mp911de commented on src/test/java/org/springframework/data/redis/connection/lettuce/LettuceConvertersUnitTests.java
> +		assertThat(redisURI.toString()).isEqualTo("redis-sentinel://app:*********************************@127.0.0.1,127.0.0.1:26380?sentinelMasterId=mymaster");
Please rewrite this check to inspect the `password` property of each sentinel URI (`RedisURI.getSentinels()`). The `toString` check performs a very strict test on unrelated internals and also the rendering of the password isn't part of any API contract.

2022-01-06 15:03 UTC, vikasgarghb commented
@mp911de Can this be approved, merged and made part of the next release?

2022-01-07 08:07 UTC, mp911de commented
Thanks a lot. I'm picking up this PR from here.

2022-01-07 10:10 UTC, mp911de commented
Thank you for your contribution. That's merged and polished now.

2022-01-07 10:10 UTC, closed without merging