Adds support for Redis setGet command
spring-projects/spring-data-redis pull request #3017
Opened 2024-10-10 13:26 UTC by marcingrzejszczak

fixes #2853

2024-10-10 13:42 UTC, mp911de requested changes
Some reactive and interface bits are missing. Care to have a look?

2024-10-10 13:42 UTC, mp911de commented on src/main/java/org/springframework/data/redis/connection/ReactiveStringCommands.java
> +		private boolean get;
That isn't going to work as the `set` API returns a boolean response.

2024-10-10 13:42 UTC, mp911de commented on src/main/java/org/springframework/data/redis/connection/ReactiveStringCommands.java
> +	Flux<ByteBufferResponse<SetCommand>> setGet(ByteBuffer key, ByteBuffer value, Expiration expiration, SetOption option);
Here we need both signatures, `Mono<ByteBuffer> setGet(ByteBuffer key, ByteBuffer value, Expiration expiration, SetOption option) {` and `Flux<ByteBufferResponse<SetCommand>> set(Publisher<SetCommand> commands);`

The first one delegates to the latter.

2024-10-10 13:42 UTC, mp911de commented on src/main/java/org/springframework/data/redis/core/ValueOperations.java
> +	V setGet(K key, V value, long timeout, TimeUnit unit);
You might want to update `BoundValueOperations` (the interface) and `ReactiveValueOperations` as well.

2024-10-11 15:34 UTC, marcingrzejszczak commented
Changes applied

2025-02-24 08:51 UTC, closed without merging